# Generated by Django 5.1.6 on 2025-02-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_photo_alter_news_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
    ]
