# Generated by Django 5.1.6 on 2025-02-26 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('946c418b-8f9e-4879-bbc1-8da2623a1342'), editable=False, primary_key=True, serialize=False),
        ),
    ]
