# Generated by Django 5.1.6 on 2025-02-26 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a537b2c5-2d0e-482c-8a64-90aef98ac390'), editable=False, primary_key=True, serialize=False),
        ),
    ]
