# Generated by Django 5.1.6 on 2025-02-26 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4608c189-7f9f-4391-961c-50da854f73ff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
