# Generated by Django 5.1.6 on 2025-02-26 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f0e4dee-8730-4ac8-a4ce-ea06c3c5609c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
