# Generated by Django 5.1.6 on 2025-02-26 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('609a13ea-f492-434c-9a33-513be18f386b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
