# Generated by Django 5.1.6 on 2025-02-26 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21801ae1-6db8-4883-b06e-9ac9f3d4eee0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
