# Generated by Django 5.1.6 on 2025-02-26 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6793dfd3-8dd5-4dee-ad4e-affa575ac772'), editable=False, primary_key=True, serialize=False),
        ),
    ]
