# Generated by Django 5.1.6 on 2025-02-26 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02655bbf-f448-4d66-a455-9a6c4682d21e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
