# Generated by Django 5.1.6 on 2025-02-26 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73cec61b-d001-4201-b38b-7439b87547b9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
