# Generated by Django 5.1.6 on 2025-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Очікує розгляду'), ('in_progress', 'В обробці'), ('resolved', 'Вирішено')], default='pending', max_length=50)),
            ],
        ),
    ]
