# Generated by Django 5.1.6 on 2025-02-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0001_initial'),
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='user.user'),
            preserve_default=False,
        ),
    ]
